export const CON_HOME= "/home";
export const CON_LOGIN= "/";
export const CON_DH = "/desarrollohumano";
export const CON_DH_BIENESTAR = "/desarrollohumano/bienestar";
export const CON_DH_BIENESTAR_GALERIA = "/desarrollohumano/bienestar/galeria";
export const CON_DH_BIENESTAR_ALIADOS = "/desarrollohumano/bienestar/aliados";
export const CON_DH_BIENESTAR_APOYO = "/desarrollohumano/bienestar/apoyo";
export const CON_DH_BIENESTAR_CONVENIO= "/desarrollohumano/bienestar/convenios";
export const CON_DH_FYD = "/desarrollohumano/formacion";
export const CON_DH_ADMON = "/desarrollohumano/admonp";
export const CON_DH_RELACIONES = "/desarrollohumano/relaciones";
export const CON_DH_SELECCION = "/desarrollo/humano/seleccion";
export const CON_DH_SST= "/desarrollohumano/seguridadysalud" ;
export const CON_DH_SST_COVID= "/desarrollohumano/seguridadysalud/covid";
export const CON_DH_SST_COVID_GALERIA= "/desarrollohumano/seguridadysalud/covid/comunicados";
export const CON_CALIDAD = "/calidad";
export const CON_CALIDAD_CORE = "/calidad/calidad";
export const CON_CALIDAD_NOTICIAS = "/calidad/noticias";
export const CON_CALIDAD_HABLADORES = "/calidad/habladores";
export const CON_CALIDAD_INDICADORES = "/calidad/indicadores";
export const CON_CALIDAD_PROCEDIMIENTOS = "/calidad/procedimientos";
export const CON_CALIDAD_REQUISITOS = "/calidad/requisitos";
export const CON_MEDIOAMBIENTE = "/medioambiente";
export const CON_ACADEMIA = "/academia"
export const CON_ACADEMIA_ARTE = "/academia/arteycultura"
export const CON_ACADEMIA_EMPODERAMIENTO= "/academia/empoderamiento"
export const CON_ACADEMIA_EMPODERAMIENTO_FORMACIONES= "/academia/empoderamiento/formaciones"
export const CON_ACADEMIA_BI_VIDEOS= "/academia/bienestar/videos"
export const CON_ACADEMIA_CURSO = "/academia/curso"
export const CON_ACADEMIA_CURSO2 = "/academia/curso2"
export const CON_ACADEMIA_CURSO3 = "/academia/curso3"
export const CON_ACADEMIA_BIENESTAR = "/academia/bienestar"
export const CON_ACADEMIA_CONCIENCIA = "/academia/conciencia"
export const CON_SOSTENIBILIDAD = "/sostenibilidad"
export const CON_SOSTENIBILIDAD_CAJAMARCA= "/sostenibilidad/cajamarca"
export const CON_SOSTENIBILIDAD_CHOCONTA="/sostenibilidad/choconta"
export const CON_SOSTENIBILIDAD_GUAITARILLA="/sostenibilidad/guaitarilla"
export const CON_SOSTENIBILIDAD_MONTES="/sostenibilidad/montes"
export const CON_SOSTENIBILIDAD_SOCOTA="/sostenibilidad/socota"
export const CON_SOSTENIBILIDAD_TUMACO="/sosotenibilidad/tumaco"
export const CON_SOSTENIBILIDAD_USME="/sostenibilidad/usme"
export const CON_SOSTENIBILIDAD_GUAMEZ="/sostenibilidad/valleguamez"
export const CON_SOSTENIBILIDAD_VIGIA= "/sostenibilidad/vigia"
export const CON_NUESTRAEMPRESA_CULTURA= "/nuestraempresa"
export const CON_EMPRESASB= "/empresab"
export const CON_ACTUALIZATE= "/actualizate"
export const CON_NUESTRAEMPRESA_GENTE= "/gente"
export const CON_ACTUALIZATE_PODCAST = "/actualizate/podcast"
export const CON_ACTUALIZATE_BEATRIZ= "/creceinspirate"
export const CON_GENTE_DOMICILIARIAS = "/domiciliarias"
export const CON_GENTE_RESTAURANTES= "/restaurantes"
export const CON_GENTE_CALL = "/callcenter"
export const CON_GENTE_CAMION= "/camionheladero"
export const CON_GENTE_COCINA= "/cocinaoculta"
