export const CON_HOME= "/home";
export const CON_VACUNACION="/vacunacion";
export const CON_VACUNACION_GALERIA="/vacunacion/galeria";
export const CON_LOGIN= "/";
export const CON_TUTORIAL= "/guia";
export const CON_DH = "/desarrollohumano";
export const CON_DH_BIENESTAR = "/desarrollohumano/bienestar";
export const CON_DH_BIENESTAR_GALERIA = "/desarrollohumano/bienestar/galeria";
export const CON_DH_BIENESTAR_ALIADOS = "/desarrollohumano/bienestar/aliados";
export const CON_DH_BIENESTAR_APOYO = "/desarrollohumano/bienestar/apoyo";
export const CON_DH_BIENESTAR_CONVENIO= "/desarrollohumano/bienestar/convenios";
export const CON_DH_FYD = "/desarrollohumano/formacion";
export const CON_DH_ADMON = "/desarrollohumano/admonp";
export const CON_DH_RELACIONES = "/desarrollohumano/relaciones";
export const CON_DH_SELECCION = "/desarrollo/humano/seleccion";
export const CON_DH_SST= "/desarrollohumano/seguridadysalud" ;
export const CON_DH_SST_COVID= "/desarrollohumano/seguridadysalud/covid";
export const CON_DH_SST_COVID_GALERIA= "/desarrollohumano/seguridadysalud/covid/comunicados";
export const CON_CALIDAD = "/calidad";
export const CON_CALIDAD_CORE = "/calidad/calidad";
export const CON_CALIDAD_NOTICIAS = "/calidad/noticias";
export const CON_CALIDAD_NOTICIAS_ALERGENOS="/calidad/noticias/alergenos"
export const CON_CALIDAD_NOTICIAS_DOCUMENTACION="/calidad/noticias/documentacion"
export const CON_CALIDAD_NOTICIAS_LYD="/calidad/noticias/lyd"
export const CON_CALIDAD_NOTICIAS_PLAGAS="/calidad/noticias/plagas"
export const CON_CALIDAD_NOTICIAS_PRODUCTO="/calidad/noticias/producto"
export const CON_CALIDAD_HABLADORES = "/calidad/habladores";
export const CON_CALIDAD_INDICADORES = "/calidad/indicadores";
export const CON_CALIDAD_PROCEDIMIENTOS = "/calidad/procedimientos";
export const CON_CALIDAD_REQUISITOS = "/calidad/requisitos";
export const CON_CALIDAD_PROGRAMAS= "/calidad/programas";
export const CON_MEDIOAMBIENTE = "/medioambiente";
export const CON_MEDIOAMBIENTE_ASPECTOSGENERALES= "/medioambiente/aspectosgenerales"
export const CON_MA_ASPECTOS_AGUARESIDUAL= "/ma/aspectosgenerales/aguaresidual"
export const CON_MA_ASPECTOS_ENERGIA="/ma/aspectosgenerales/energia"
export const CON_MA_ASPECTOS_AGUAPOTABLE= "/ma/aspectosgenerales/aguapotable"
export const CON_MA_ASPECTOS_RESIDUOS="/ma/aspectosgenerales/residuos"
export const CON_MA_ASPECTOS_ECONOMIA="/ma/aspectosgenerales/economia"
export const CON_MEDIOAMBIENTE_MUNDODEHOY= "/medioambiente/mundodehoy"
export const CON_MEDIOAMBIENTE_ASPECTOSAMBIENTALES="/medioambiente/aspectosambientales"
export const CON_MEDIOAMBIENTE_NOTICIAS="/medioambiente/noticias"
export const CON_MEDIOAMBIENTE_INDICADORES="/medioambiente/indicadores"
export const CON_MEDIOAMBIENTE_NOTICIAS_AGUAPOTABLE="/medioambiente/noticias/aguapotable"
export const CON_MEDIOAMBIENTE_NOTICIAS_AGUARESIDUAL="/medioambiente/noticias/aguaresidual"
export const CON_MEDIOAMBIENTE_NOTICIAS_PEDIDOS="/medioambiente/noticias/pedidos"
export const CON_MEDIOAMBIENTE_NOTICIAS_RESIDUOS="/medioambiente/noticias/residuos"
export const CON_MA_ASPECTOSAMBIENTALES_COCINACENTRAL="/medioambiente/aspectosambientales/cocinacentral"
export const CON_MA_ASPECTOSAMBIENTALES_COCINABUCARA="/medioambiente/aspectosambientales/cocinabucaramanga"
export const CON_MA_ASPECTOSAMBIENTALES_PDVCC="/medioambiente/aspectosambientales/pdvcc" 
export const CON_MA_ASPECTOSAMBIENTALES_PDVCALLE="/medioambiente/aspectosambientales/pdvcalle"
export const CON_ACADEMIA = "/academia"
export const CON_ACADEMIA_ARTE = "/academia/arteycultura"
export const CON_ACADEMIA_EMPODERAMIENTO= "/academia/empoderamiento"
export const CON_ACADEMIA_EMPODERAMIENTO_FORMACIONES= "/academia/empoderamiento/formaciones"
export const CON_ACADEMIA_BI_VIDEOS= "/academia/bienestar/videos"
export const CON_ACADEMIA_CURSO = "/academia/curso"
export const CON_ACADEMIA_CURSO2 = "/academia/curso2"
export const CON_ACADEMIA_CURSO3 = "/academia/curso3"
export const CON_ACADEMIA_BIENESTAR = "/academia/bienestar"
export const CON_ACADEMIA_CONCIENCIA = "/academia/conciencia"
export const CON_SOSTENIBILIDAD = "/sostenibilidad"
export const CON_SOSTENIBILIDAD_CAJAMARCA= "/sostenibilidad/cajamarca"
export const CON_SOSTENIBILIDAD_CHOCONTA="/sostenibilidad/choconta"
export const CON_SOSTENIBILIDAD_GUAITARILLA="/sostenibilidad/guaitarilla"
export const CON_SOSTENIBILIDAD_MONTES="/sostenibilidad/montes"
export const CON_SOSTENIBILIDAD_SOCOTA="/sostenibilidad/socota"
export const CON_SOSTENIBILIDAD_TUMACO="/sosotenibilidad/tumaco"
export const CON_SOSTENIBILIDAD_USME="/sostenibilidad/usme"
export const CON_SOSTENIBILIDAD_GUAMEZ="/sostenibilidad/valleguamez"
export const CON_SOSTENIBILIDAD_VIGIA= "/sostenibilidad/vigia"
export const CON_NUESTRAEMPRESA_CULTURA= "/nuestraempresa"
export const CON_EMPRESASB= "/empresab"
export const CON_ACTUALIZATE= "/actualizate"
export const CON_NUESTRAEMPRESA_GENTE= "/gente"
export const CON_ACTUALIZATE_PODCAST = "/actualizate/podcast"
export const CON_ACTUALIZATE_BEATRIZ= "/creceinspirate"
export const CON_GENTE_DOMICILIARIAS = "/domiciliarias"
export const CON_GENTE_RESTAURANTES= "/galeria/restaurantes"
export const CON_GENTE_HELADERIAS= "/galeria/heladerias"
export const CON_GENTE_CALL = "/callcenter"
export const CON_GENTE_CAMION= "/camionheladero"
export const CON_GENTE_COCINA= "/cocinaoculta"
export const CON_FUNDADORES= "/fundadores"
export const CON_GERENCIA="/gerencia"
export const CON_RECONOCIMIENTOS = "/reconocimientos"
export const CON_COMPRAS="/compras"
export const CON_FINANCIERA="/financiera"
export const CON_FINANCIERA_PLANEACION="/financiera/planeacion"
export const CON_FINANCIERA_NOMINA="/financiera/nomina"
export const CON_FINANCIERA_TESORERIA="/financiera/tesoreria"
export const CON_FINANCIERA_CONTABILIDAD="/financiera/contabilidad"
export const CON_LEGAL= "/legal"
export const CON_LEGAL_CENTROSERVICIO= "/legal/centrodeservicio"
export const CON_LEGAL_CENTROSERVICIO_DIRADMON="/legal/centrodeservicio/directorioadmon"
export const CON_LEGAL_CENTROSERVICIO_DIRPDV="/legal/centrodeservicio/directoriopdv"
export const CON_LEGAL_GESTIONDOCUMENTAL= "/legal/gestiondocumental"
export const CON_LEGAL_INMUEBLES= "/legal/inmuebles"
export const CON_LEGAL_SEGURIDAD= "/legal/seguridad"
export const CON_LOGISTICA="/logistica"
export const CON_MANTENIMIENTO="/mantenimiento"
export const CON_MERCADEO="/mercadeoeinnovacion"
export const CON_HELADERIAS="/heladerias"
export const CON_RESTAURANTES="/restaurantes"
export const CON_PLANTA_HELADOS="/plantahelados"
export const CON_PLANTA_PRODUCCION="/plantaproduccion"
export const CON_SARGLAFT="/sarglaft"
export const CON_SARGLAFT_PTEE="/sarglaft/ptee"
export const CON_SARGLAFT_INFO="/sarglaft/info"
export const CON_SARGLAFT_PTEE_VIDEOS= "/sarglaft/ptee/videos"
export const CON_SARGLAFT_INFO_VIDEOS="/sarglaft/info/videos"
export const CON_TECNOLOGIA="/tecnologia"
export const CON_UBICACIONES="/ubicaciones"
export const CON_FORM_FACTURACION="/facturacionelectronica"
export const CON_ADMIN_FACTURACION="/adminfacturacion"
